### ISSUE TITLE
bootstrap update to 4.+

### ISSUE THREAD

**Issue by ignalex** [iag-geo/bootleaf#15]
if possible or in the plans?

**Comment by growe19** [comment]
+1

**Comment by slead** [comment]
I wasn't planning to update Bootleaf to Bootstrap 4.

Bootstrap 4 wasn't quite ready when we started Bootleaf, so I went with the older, stable version 3. Now that Bootstrap 4 is out I use it for all new projects, but I can't see any real reason to update Bootleaf to Bootstrap 4.

If you wanted to do it, the majority of the changes would be in Index.html - you'd point to the latest Bootstrap 4 CSS and JS files, and update the markup.

Looking quickly at the app, there isn't that much to change as it's just the main map element, plus the sidebar that contains the query and identify results. However, I can see that I've been a bit lazy and there are a few small HTML elements built at run-time in the app.js file, for example:

```
function resetQueryOutputTable(){
  $("#queryResults").html('<span id="ajaxLoading"></span><table id="tblQueryResults" class="table table-condensed table-hover"></table><div id="exportButtons"></div>');
}
```
They should really have been defined using handlebars.js templates in the index.html file, like the query results:

```
<!-- handlebars templates -->
    <script id="query-template" type="text/x-handlebars-template">
      <div id="frmQueryWidget" class="well well-sm">
        <div class="form-group">
```

So you may need to check app.js to find other elements which require updating to Bootstrap 4 too.

I probably won't have time to do this in the near future, but I'll do it if I can find the time. Alternatively, feel free to make the changes and submit a pull request!

Thanks,
Steve

**Comment by growe19** [comment]
I've been attempting to go through it since I posted my +1 reply. The most annoying thing to fix I think is the navbar element. Still troubling me. I've updated everything that links to a CDN to the latest version. Haven't come too unstuck yet. I have no idea what I'm really doing, just giving it a go.

**Comment by growe19** [comment]
Overall I think it's only a couple of hours work if you know what you're doing (which I don't).

**Comment by slead** [comment]
cool, keep us posted on your progress. I'm over-committed for the next month or so, but I'll take a look if time permits after that

**Comment by slead** [comment]
This was done by @ahmednoureldeen and has been merged into the master branch
