### ISSUE TITLE
json not loading on trunk clone

### ISSUE THREAD

**Issue by hardreddata** [iag-geo/bootleaf#22]
```
git clone https://github.com/iag-geo/bootleaf
```
and then opening index.html in a web browser complains about the theatres and the museums. 

I suspect some online library has changed but don't know enough to troubleshoot. Earlier Bootleaf versions (admittedly the trunk doesn't change much) are also not behaving.

**Comment by slead** [comment]
Hi Russell,

You may need to check the permissions on the `data `folder and its items. Verify that you can access the geojson in the browser. In my case this is accessed via:

http://localhost/demos/bootleaf/data/museums.geojson

If you get an error, check the permissions on the files, which should be in your web server's directory, not the file system. eg on Windows this will be `c:/inetpub/wwwroot/bootleaf/data`, and on a Mac it'll be `/Library/WebServer/Documents/bootleaf/data`. Does that help?

**Comment by hardreddata** [comment]
Thanks for the prompt response.

I found Bootleaf really useful accessing it on disk rather than accessing via hosting it as a webpage. I am fairly certain this used to work. Just opening up the index.html direct from the file explorer. I have encountered this on Windows 10 and Ubuntu linux.

If this isn't impacting anyone else I am happy to see the issue closed.

**Comment by slead** [comment]
It may work sometimes, but it's always better to use the web server where you can. This also simulates more closely how it'll appear if you do host your apps online. 

Good luck,
Steve
