### ISSUE TITLE
How to display Layer Legend?

### ISSUE THREAD

**Issue by renelikestacos** [iag-geo/bootleaf#29]
It is more a question than an issue. I can see in the app.js you have taken a legend of a layer into account. I wonder if it is possible to make it show a legend? I tried with the WFS and GeoJSON Layers but without any success. I would appreciate it.

**Comment by slead** [comment]
That's a great question. As you noticed there is stub code in there to create a simple legend patch, which depends on matching CSS to style the legend item. 

From memory, this was used to create a simple legend item in the Table of Contents, and worked best when a single dataset was used with multiple definition queries to create a series of layers, each of which could be styled separately (eg a blue circle for class A, a red square for class B, etc).

Aside from that I think the only other way we used legends was to add a hard-coded image in a modal dialog, and add this to the Tools menu.

You could look at other Leaflet applications of legends and incorporate those ideas, eg the [Choropleth](https://leafletjs.com/examples/choropleth/) demo which includes a legend.

As always, feel free to submit a pull-request if you come up with something useful!

**Comment by renelikestacos** [comment]
Thanks Stephen. I might add them hard-coded. To be honest, I am having a hard time to add any plugin in the framework (not a lot of JS experience). It would be great to have a tutorial on how doing it.

**Comment by slead** [comment]
You asked this question ages ago, and I finally found the answer. If you use the `legendClass` keyword in the config file, the framework creates an item in the table of contents, which you can style using CSS.

From the config file:

```
"id": "events_tropicalCyclone",
"name": "Events - Tropical cyclone",
"where": "Phenomenon = 'Tropical Cyclone'",
"type": "agsFeatureLayer",
"legendClass": "tropical_cyclone",
```

In the CSS file:

```
.legend {
  padding: 0px 10px 0px 5px;
  margin-right: 5px;
}

.tropical_cyclone {
  background-color: #047510;
}
```

This is how it appears in the TOC:

![Screen Shot 2020-11-11 at 8 37 50 pm](https://user-images.githubusercontent.com/133596/98794968-c6c09380-245d-11eb-8245-fae969f325f5.png)

Hope this helps.
