### ISSUE TITLE
Where to add a Google API key for geocoder?

### ISSUE THREAD

**Issue by jamesinealing** [iag-geo/bootleaf#3]
Hi, have used Bootleaf for years and this is a really great step forward on something that was already good!

Hopefully a simple request, but I can't seem to find an answer for myself!  Google's Geocoder now needs an API key so I was wondering where I need to add this?  I suspect I could hard code it into Control.Geocoder.js but I don't really want to do this!

I did try

		"leafletGeocoder": {
			//https://github.com/perliedman/leaflet-control-geocoder
			"key": "AIza..........................................UGiCk",
			"collapsed": false,
			"position": "bottomleft",
			"placeholder": "Search for a location",
			"type": "Google", // OpenStreetMap, Google, ArcGIS
			//"suffix": "Australia" // optional keyword to append to every search
		},

but that doesn't seem to pass the key in the request.

Thanks

**Comment by slead** [comment]
Hi James,

I'm really glad that you find it useful!

I had to make some changes to the leaflet geocoder in order to get it to append the Google Maps API key. I also added this option to the Bootleaf config.js file. If you fetch the latest version of this repo you should see the changes:

```
// config.js
"leafletGeocoder": {
  "type": "Google", 
  "key": "AIzaS....sbW_E", // when using the Google geocoder, include your Google Maps API key 
},
```

```
// Control.geocoder.js, in the plugins directory, around line 471
  // SL. This section wasn't working in the original code so I modified it to suit the Google Maps key setting in the Bootleaf config file
  if (this._key && this._key.key) {
    params.key = this._key.key;
}
```

**Comment by jamesinealing** [comment]
Works a treat, thanks for such a prompt response
