### ISSUE TITLE
Using Bing tiles?

### ISSUE THREAD

**Issue by jamesinealing** [iag-geo/bootleaf#4]
Hi, can I ask how you configure the Bing tiles? I can see where to add the API key, and the docs here have the names of three layer types, but /src/js/app.js doesn't appear to have them defined.

**Comment by slead** [comment]
Hi James,

From memory, we were initially using Bing tiles but switched to MapBox a while ago, and I may have removed the Bing tiles code (without updating the readme).

Let me look into it - it may take a couple of days as I'm currently travelling. Alternatively feel free to submit a PR if you want to look into it yourself.

Cheers,
Steve

**Comment by jamesinealing** [comment]
Hi, thanks for the quick reply. I used this framework to create https://astreetnearyou.org (though it is almost all custom code now!) and it has had 80,000 visits since I launched yesterday afternoon. Mapbox bill currently at about $170!

**Comment by slead** [comment]
ouch! But congrats on a viral hit. You could try using OpenStreetMap as the basemap? https://github.com/iag-geo/bootleaf#basemaps

**Comment by slead** [comment]
I just restored the Bing Maps code - fetch the latest commit to see it. I don't have a Bing Maps key to test it, but I can see a Bing Maps `invalid credentials` error message when I try to use the Aerial basemap, so I figure it should work if you do have a valid Bing Maps key (https://msdn.microsoft.com/en-us/library/ff428642.aspx)

let me know how you go

**Comment by jamesinealing** [comment]
I built it on that but their terms of service are quite clear it's not for big sites. At least that's how I read it. Certainly don't want to abuse it.  I've just switched to Esri which seems to work with no account or key. I couldn't see any restrictions on their site - do you know what the deal is?

**Comment by slead** [comment]
re: esri basemap limitations, that's a great question that I have no answer to. I just googled to find https://doc.arcgis.com/en/arcgis-online/reference/transaction-limits.htm which shows the limitations.

But - bootleaf uses the Esri basemaps from https://esri.github.io/esri-leaflet/api-reference/layers/basemap-layer.html which doesn't actually ask for your credentials. So I guess it's free and unlimited?

Anyway, Bing Maps are restored in the latest commit so hopefully you have some options now. Good luck!

**Comment by jamesinealing** [comment]
Oh, that's great, thank you. The good thing with Bing is they have I think an *annual* limit and if I burn it in the next 24 hours, so what?!  What a fantastic community we have - I've had help from so many places today trying to keep this thing up and running!

**Comment by slead** [comment]
:thumbsup:
