### ISSUE TITLE
Add ability to Identify features

### ISSUE THREAD

**Issue by slead** [iag-geo/bootleaf#4]
onEachFeature on layers which support this, or use https://github.com/mapbox/leaflet-pip otherwise

**Comment by iag-hugh** [comment]
Would be good to evolve this in the future to support "pretty field names".

e.g. "nrma_pif_cnt" = "NRMA Policy Count"

**Comment by slead** [comment]
patience, Grasshopper ;)

**Comment by iag-hugh** [comment]
I did add "evolve" and "future" to the issue ;-)

**Comment by slead** [comment]
![identify](https://cloud.githubusercontent.com/assets/133596/21373958/fc9f0722-c776-11e6-9179-f3cc0e79902c.PNG)

Alias is used if present, otherwise it defaults to the field name
