### ISSUE TITLE
Error message when geoJson layers are not at the top of layers list

### ISSUE THREAD

**Issue by SchroeC** [iag-geo/bootleaf#5]
Hello,

I'd like to thank IAG for providing boot-leaf open source and Stephan Lead for the work he’s done putting the framework and documentation together. I'm a novice web developer experimenting with your source code though django web framework.

I've found what seems to be an issue in the way boot-leaf manages layers. If I move the example geojson layers to a different position in the layers list I get the following error when the map loads. This error seems to appear if any of the geojson are not at the top of the list. The functionality of the Map appears to be unaffected (all layers load, just the error message appears).

![untitled](https://user-images.githubusercontent.com/45743999/49754574-a84f2d80-fc73-11e8-84b1-5b53462455bd.png)

Aside from from the config file, below is list of modifications I've made to the bootleaf source:

## [Installation](#installation)

Package was split into the following to match Django filing structure:
  - Project specific static files moved to Project-->static
  - Project specific index file was moved into temlates-->Project
  - The remaining folder structure was moved to static

  The index file supplied with the original package was modified to include django
  tagging of its static links and were routed to the correct directory based on the
  package split discussed above.

## [Customizations](#customizations)

 - added resize #sidebar in bootleaf-->style.css
 - changed .panel-heading, .panel-body & .feature-row width to 100%
   in bootleaf-->style.css

## [Fixes](#fixes)

  - changed typo in config file for esri basemap layer topographic

**Comment by slead** [comment]
I can reproduce the error when the JSON layers aren't found at the top of the list - I'll look into it as soon as possible.

For now, the workaround is - put them at the top of the list ;)

It's cool to see that you're using this in Django, I'd love to see the finished app when you're done

**Comment by slead** [comment]
This should now be fixed in the latest version. The change is around line 357 of `app.js`:

```
// Add the layer to the map if it's not hidden. geoJSON layers are added after their Ajax call has completed
if (!layerConfig.hidden && layerConfig.type !== 'geoJSON') {
  addLayer(layer);
}
```

Let me know if you see any further issues.

**Comment by SchroeC** [comment]
Hey! wow fast turn around. Yes I'll post any issues I find and I'll share what I end up with in the end.

Thanks!
