### ISSUE TITLE
Mention esri-leaflet Terms in README

### ISSUE THREAD

**Issue by rnuske** [iag-geo/bootleaf#9]
ESRI seems to have firm ideas under which [Terms](https://github.com/Esri/esri-leaflet#terms) one can use esri-leaflet. For example, one needs to buy one of their products if using esri-leaflet for government or business purposes. At least that's what I understood, I might be wrong.

If these terms apply to bootleaf (which I guess is the case), it might be good to inform users about it upfront in the `README.md`.

**Comment by slead** [comment]
thanks, I'll add a reference to https://github.com/esri/esri-leaflet#terms to the readme

It looks like the [Esri attribution](https://developers.arcgis.com/terms/attribution/) is automatically handled by them

**Comment by slead** [comment]
done now. thanks again

**Comment by rnuske** [comment]
Since the [esri-leaflet Term](https://github.com/Esri/esri-leaflet#terms) first talks in generally about the app

> If your app is for public, non-revenue generating, non-government, non-commercial use, the free Essentials Developer Plan is sufficient. If you're going to generate revenue or are using the app for government or business purposes, you'll have to purchase one of the products below:

and than later about maps displyed within the app,

> If you display an ArcGIS Online service in any Leaflet application, we require that you display Esri attribution and recognize data providers.

I assume that the first paragraph describes what is needed if one wants to use the `esri-leaflet` code no matter which map one displays within the app. That could mean that I need some `ArcGIS Developer Subscriptions` at least the `Essentials Developer Plan` if i want to use bootleaf.

They seem to differentiate between displaying their maps and using their code (esri-leaflet)

**Comment by slead** [comment]
Thanks, I expanded upon the description of this in the readme:

`Note - Bootleaf uses the Esri-Leaflet plugin, in order to support ArcGIS layers and display Esri basemaps. Please note the Esri usage terms before using this.`
